"""empty message

Revision ID: 4981c4149302
Revises: 
Create Date: 2025-03-07 10:44:31.398406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4981c4149302'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minigames',
    sa.Column('id_minigame', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('points_per_win', sa.Integer(), nullable=False),
    sa.Column('lives', sa.Integer(), nullable=True),
    sa.Column('game_time', sa.Float(), nullable=True),
    sa.Column('click_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_minigame'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('user_img', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=1000), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('played_games',
    sa.Column('id_played_games', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('minigame_id', sa.Integer(), nullable=True),
    sa.Column('game_data', sa.String(length=3000), nullable=False),
    sa.Column('game_points', sa.Integer(), nullable=False),
    sa.Column('record', sa.Integer(), nullable=True),
    sa.Column('click_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['minigame_id'], ['minigames.id_minigame'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_played_games')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('played_games')
    op.drop_table('user')
    op.drop_table('minigames')
    # ### end Alembic commands ###
