"""empty message

Revision ID: 59985b1b1cfd
Revises: 4981c4149302
Create Date: 2025-03-07 11:16:04.366809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59985b1b1cfd'
down_revision = '4981c4149302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('played_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mithril_per_second', sa.Float(), nullable=True))
        batch_op.drop_column('click_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('played_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('click_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('mithril_per_second')

    # ### end Alembic commands ###
